### ISSUE TITLE
no Connection over Internet.

### ISSUE THREAD

**Issue by nico00771** [xosg/peer-stream#10]
Hello, thanks for your lightweight WebRTC.
I have a problem when I want to connect via internet.
 unfortunately no connection is established.
with the heavy sdk kit from Unreal it works without any problems, I use the same stun server in each case.

do you have any ideas ?

**Comment by xosg** [comment]
use public stun servers or setup ur own stun server.

![image](https://user-images.githubusercontent.com/28730445/168587391-f6cbf792-1ae0-488f-85b5-9dcc72e72bde.png)
