### ISSUE TITLE
The signal service has been reset. Why

### ISSUE THREAD

**Issue by lishu2006ll** [xosg/peer-stream#11]
this is very unnormal style: 
❌ signaler closed: 1
index.js:7 ✅ connected to ws://localhost:8989/
peer-stream.js:187 ↓↓ ❌ Engine:8888 stopped
peer-stream.js:187 ↓↓ ✅ Engine:8888 started
index.js:7 ❌ signaler closed: 1

**Comment by xosg** [comment]
when a new UE5 instance connects to signal.js, all connected players will be reset.

![image](https://user-images.githubusercontent.com/28730445/168588103-d38ea54b-a0f7-428e-8d71-09a9a4d6d015.png)
