### ISSUE TITLE
请问如何设置UE使用的webRTC UDP 端口范围呢？ How to use specific UDP ports for pixelstreaming‘s webRTC

### ISSUE THREAD

**Issue by Wjqshark** [xosg/peer-stream#8]
现在看UE使用UDP端口完全是随机选，UE官方文档也完全没有说明。使用了coturn 作为Turn服务也只能设置从 Turn转发出的udp的端口，无法限制UE的端口。 查到浏览器端可以从policy 设置 WebRtcUdpPortRange 去进行设置。 从UE侧有什么方式去限制呢？

**Comment by xosg** [comment]
从UE侧那就得修改后端源码了，本仓库里面不涉及WebRTC后端。。

**Comment by 20221103s** [comment]
@g0415shenw 这个用TURN可以解决了啊

**Comment by xosg** [comment]
用turn可以实现端口限制范围

**Comment by Cat-Wong** [comment]
> 现在看UE使用UDP端口完全是随机选，UE官方文档也完全没有说明。使用了coturn 作为Turn服务也只能设置从 Turn转发出的udp的端口，无法限制UE的端口。 查到浏览器端可以从policy 设置 WebRtcUdpPortRange 去进行设置。 从UE侧有什么方式去限制呢？

请问找到限制UDP端口的方法了吗

**Comment by Wjqshark** [comment]
使用coturn做中转服务，可以限制使用的端口。 
在 etc/turnserver.conf.default 中
min-port=49152
max-port=65535

**Comment by Cat-Wong** [comment]
> 使用coturn做中转服务，可以限制使用的端口。 在 etc/turnserver.conf.default 中 min-port=49152 max-port=65535

UE5打包后，像素流文件夹中的coturn 没有turnserver.conf.default， 是不是需要在服务器上另外构建一个coturn服务，然后用来中转UE呢，能否留一个联系方式解答下，有偿

**Comment by 20221103s** [comment]
感谢您为我们提出的问题
您的问题有点复杂，邮件可能不方便讨论，可以加入QQ群聊@管理员交流
另：本周五晚8点有技术交流，欢迎来玩






20230924
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "inveta/peer-stream"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月16日(星期二) 下午3:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [inveta/peer-stream] 请问如何设置UE使用的webRTC UDP 端口范围呢？ How to use specific UDP ports for pixelstreaming‘s webRTC (Issue #8)





  
使用coturn做中转服务，可以限制使用的端口。 在 etc/turnserver.conf.default 中 min-port=49152 max-port=65535
  
UE5打包后，像素流文件夹中的coturn 没有turnserver.conf.default， 是不是需要在服务器上另外构建一个coturn服务，然后用来中转UE呢，能否留一个联系方式解答下，有偿
